#!/bin/sh
# usage: genprogs.sh out.c name:image ...
# Generates a C file that embeds each program image (.incbin) and a table describing them.
out="$1"; shift
{
	echo '/* Generated by tools/genprogs.sh - do not edit. */'
	echo '#include "user.h"'
	echo
	for e in "$@"; do
		n="${e%%:*}"
		echo "extern const uint8_t p_${n}_start[], p_${n}_end[];"
	done
	echo
	for e in "$@"; do
		n="${e%%:*}"; f="${e#*:}"
		printf '__asm__(".section .rodata\\n.globl _p_%s_start\\n_p_%s_start:\\n.incbin \\"%s\\"\\n.globl _p_%s_end\\n_p_%s_end:\\n.text\\n");\n' "$n" "$n" "$f" "$n" "$n"
	done
	echo
	echo 'const struct builtin_prog builtin_progs[] = {'
	for e in "$@"; do
		n="${e%%:*}"
		echo "	{ \"$n\", p_${n}_start, p_${n}_end },"
	done
	echo '};'
	echo "const unsigned builtin_nprogs = $#;"
} > "$out"
